# Generated by Django 4.2.10 on 2024-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0003_alter_category_options_alter_add_movies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_movies',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
