# Generated by Django 4.2.7 on 2024-02-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0004_alter_add_movies_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
